name: Auto Assign Issues to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign Bugs to panel
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/UPAM5A/gestion-interna-bugTracker/projects/2'

    - name: Assign Enhancements to panel 
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(github.event.issue.labels.*.name, 'enhancement ') ||
      with:
        project: 'https://github.com/UPAM5A/gestion-interna-bugTracker/projects/1'
